plugins {
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.gradle.maven.publish)
    id("protobuf-convention")
    id("spotless-convention")
    id("dokka-convention")
    id("errorprone-convention")
    id("android-convention")
}

android {
    namespace 'com.uber.simplestore.proto'

    defaultConfig {
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        // The following argument makes the Android Test Orchestrator run its
        // "pm clear" command after each test invocation. This command ensures
        // that the app's state is completely cleared between tests.
        testInstrumentationRunnerArguments clearPackageData: 'true'
    }

    testOptions {
        execution 'ANDROIDX_TEST_ORCHESTRATOR'
    }
}

dependencies {
    implementation project(":simplestore")
    api libs.protobuf.javalite

    testImplementation testLibs.junit
    testImplementation testLibs.truth
    testImplementation testLibs.robolectric

    androidTestImplementation testLibs.androidx.runner
    androidTestImplementation testLibs.androidx.rules
    androidTestImplementation testLibs.androidx.rules

    androidTestUtil testLibs.androidx.orchestrator
}
