import org.jetbrains.dokka.gradle.DokkaTaskPartial

plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.errorprone) apply false
    alias(libs.plugins.nullaway) apply false
    alias(libs.plugins.spotless) apply false
    alias(libs.plugins.protobuf) apply false
    alias(libs.plugins.gradle.maven.publish) apply false
    alias(libs.plugins.dokka) apply false
}

apply plugin: 'org.jetbrains.dokka'

tasks.dokkaHtmlMultiModule {
    outputDirectory.set(new File(rootDir,"docs/0.x"))
    includes.from(project.layout.projectDirectory.file("README.md"))
}
