android_library(
    name = "simplestore",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
            "//third_party:com_google_code_findbugs_jsr305",
            "//java/com/uber/simplestore/executors",
    ],
)
