android_library(name = "impl",
                srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//java/com/ubercab/simplestorage",
        "//third_party:com_google_code_findbugs_jsr305",
    ],
    exports = [
        "//java/com/ubercab/simplestorage",
    ],
)
