android_local_test(
    name = "SimpleStoreImplTest",
    srcs = ["SimpleStoreImplTest.java"],
    deps = [
        "//java/com/ubercab/simplestorage/impl",
        "@robolectric//bazel:robolectric",
    ],
)
