android_library(
    name = "impl",
    srcs = glob(["*.java"]),
    visibility = ["//java/com/uber/simplestore/proto:__pkg__"],
    deps = [
      "//java/com/uber/simplestore/proto",
      "//java/com/uber/simplestore/impl",
      "//third_party:com_google_code_findbugs_jsr305",
      "//third_party:com_google_protobuf_protobuf_lite",
    ],
)