plugins {
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.spotless)
    alias(libs.plugins.dokka)
    alias(libs.plugins.gradle.maven.publish)
    id("spotless-convention")
    id("dokka-convention")
    id("errorprone-convention")
    id("android-convention")
}

android {
    namespace 'com.uber.simplestore.fakes'
}

dependencies {
    implementation project(":simplestore")
    implementation libs.guava

    testImplementation testLibs.junit
    testImplementation testLibs.truth
}
