[versions]
agp = "8.6.1"
annotation = "1.8.2"
appcompat = "1.7.0"
guava = "33.2.1-android"
kotlin = "2.0.0"
errorProne = "4.0.1"
errorProneJavaC = "9+181-r4173-1"
nullAway = "1.3.0"
spotless = "6.25.0"
protobuf = "3.22.3"
protobufPlugin = "0.9.4"
gradleMavenPublishPlugin = "0.29.0"
dokka = "1.9.20"
javaFormat = "1.17.0"

[libraries]
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
protobuf-javalite = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protobuf" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
nullaway = { group = "com.uber.nullaway", name = "nullaway", version.ref = "nullAway" }
errorprone = { group = "com.google.errorprone", name = "error_prone_core", version.ref = "errorProne" }
errorprone-javac = { group = "com.google.errorprone", name = "javac", version.ref = "errorProneJavaC" }
# Conventions
gradle-spotless-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
gradle-errorprone-plugin = { module = "net.ltgt.gradle:gradle-errorprone-plugin", version.ref = "errorProne" }
gradle-nullaway-plugin = { module = "net.ltgt.gradle:gradle-nullaway-plugin", version.ref = "nullAway" }
gradle-dokka-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
gradle-protobuf-plugin = { module = "com.google.protobuf:protobuf-gradle-plugin", version.ref = "protobufPlugin" }
gradle-android-library-plugin = { module = "com.android.library:com.android.library.gradle.plugin", version.ref = "agp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorProne" }
nullaway = { id = "net.ltgt.nullaway", version.ref = "nullAway" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
gradle-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "gradleMavenPublishPlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }