android_local_test(
    name = "SimpleStoreImplTest",
    srcs = ["SimpleStoreImplTest.java"],
    deps = [
        "//javatests/com/uber/simplestore/utils",
        "//java/com/uber/simplestore/impl",
        "//java/com/uber/simplestore/executors",
        "@robolectric//bazel:robolectric",
    ],
)
