android_library(
    name = "executors",
    srcs = glob(["*.java"]),
    visibility = [
            "//java/com/uber/simplestore:__subpackages__",
            "//javatests/com/uber/simplestore:__subpackages__",
    ],
)
